### ISSUE TITLE
chameleon "spoof media devices" breaks devices.js

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#30]
when chameleon is set to "spoof media devices", the function never returns (and the section never finishes, so the overall FP never happens), and I can't seem to catch it

any ideas? @sereneblue @kkapsner @abrahamjuliot @ beers @ coffee @ sleep

![grrr](https://user-images.githubusercontent.com/16656956/104265393-65c93200-5485-11eb-8152-0bc3ca020b62.png)

```js
function get_media_devices() {
	return new Promise(resolve => {

		function finish(result) {
			dom.eMDList.style.color = zshow
			return resolve("media_devices:"+result)
		}
		if ("mediaDevices" in navigator) {
			// enumerate
			let str="", pad=13, strPad=""
			try {
				navigator.mediaDevices.enumerateDevices().then(function(devices) {
					let arr = []
					// enumerate
					try {
						devices.forEach(function(d) {
							arr.push(d.kind)
							str += (d.kind+": ").padStart(pad)+d.deviceId
							if (d.groupId.length > 0) {
								strPad = ("group: ").padStart(pad)
								str += "<br>"+strPad+d.groupId
							}
							if (d.label.length > 0) {
								strPad = ("label: ").padStart(pad)
								str += "<br>"+strPad+d.label
							}
							str += "<br>"
						})
					} catch(e) {
						console.debug(e.name, e.message)
					}
					// output list
					if (str.length == 0) {str = "none"}
					dom.eMDList.innerHTML = str

					// count each kind
					let pretty = [], plain = [], rfphash = ""
					if (arr.length > 0) {
						arr.sort()
						let map = arr.reduce((acc, e) => acc.set(e, (acc.get(e) || 0) + 1), new Map());
						arr = [...map.entries()]
						// build pretty/plain
						for (let i=0; i < arr.length; i++) {
							let data = arr[i],
								item = data[0],
								itemcount = data[1]
							pretty.push(item + s7 +"["+ itemcount +"]" + sc)
							plain.push(item +","+ itemcount)
						}
						pretty = pretty.join(" ")
						str = plain.join(";")
						rfphash = sha1(str)
					} else {
						pretty = "none"
					}
					// RFP
					if (rfphash == "6812ba88a8eb69ed8fd02cfaecf7431b9c3d9229") {
						dom.eMD.innerHTML = pretty + (isTB ? tb_red : rfp_green)
					} else {
						dom.eMD.innerHTML = pretty + (isTB ? tb_red : rfp_red)
					}
					finish(str)
				})
				.catch(function(e) {
					dom.eMDList.innerHTML = e.name +": "+ e.message
					dom.eMD.innerHTML = e.name
					finish(e.name)
				})
			} catch(e) {
				dom.eMDList.innerHTML = zB0
				dom.eMD.innerHTML = zB0 + (isTB ? tb_red : rfp_red)
				finish(zB0)
			}
		}	else {
			dom.eMDList = zD
			dom.eMD.innerHTML = zD + (isTB ? tb_green : rfp_red)
			finish(zD)
		}
	})
}

```

**Comment by sereneblue** [comment]
@Thorin-Oakenpants This should be fixed in v0.21.14.

**Comment by Thorin-Oakenpants** [comment]
@sereneblue just tested .. still the same problem. It's weird, I can't even trap anything. What exactly does your code target: maybe that will shed a light?

**Comment by sereneblue** [comment]
@Thorin-Oakenpants Oops. It looks like I updated `Block media devices` although it didn't actually need an update. Chameleon wraps the enumerateDevices method and replaces the labels if the user has given permission for the page to access the mic/camera. I noticed that it's being called twice on the page. The first call successfully returns but the second hangs. It _should_ be straightforward but for some reason the original function call is hanging, preventing Chameleon from returning the list of devices. I'm not sure why yet but I hope to address this in the next update.

**Comment by Thorin-Oakenpants** [comment]
there shouldn't be any FF permission needed to query/enumerate the devices. I'm still confused as to why it can't be trapped

**Comment by Thorin-Oakenpants** [comment]
>  I noticed that it's being called twice on the page

Hmmm. Not seen that in my tests (enumerate devices) - maybe I need to debug it more?

If you look at my speech engines function (below) ... there's a large commented out notes in the middle about WTF I get multiple returns when the page is loaded/reloaded - but not on reruns. Now however, when generic.js lands and is waiting for the other files to land, I "prime" a couple of APIa and now that multiple results doesn't happen. 

However, I think my function, and probably the enumerate devices one, are wonky-as-a-donkey, and would prefer a proper solution rather than my current hacky workaround.

Was going to ask abraham for his drop-in-snippet for me

```js
function get_speech_engines() {
	return new Promise(resolve => {
		let t0 = performance.now()

		// output & resolve
		function display(output) {
			let detail = output, count = ""
			if (Array.isArray(output)) {
				count = s7 +"["+ output.length +"]"+ sc
				detail = output.join("<br>")
				output = sha1(output.join())
			}
			dom.sEngines.innerHTML = output + count + (output == "none" ? rfp_green : rfp_red)
			dom.sEnginesList.innerHTML = detail
			dom.sEnginesList.style.color = zshow
			if (logPerf) {debug_log("speech engines [devices]",t0)}
			return resolve("speech_engines:" + output)
		}

		if ("speechSynthesis" in window) {
			function populateVoiceList() {
				let res = []
				try {
					if(typeof speechSynthesis == "undefined") {
						return
					} else {
						let v = speechSynthesis.getVoices()
						for (let i=0; i < v.length; i++) {
							res.push(v[i].name + " (" + v[i].lang + ")" + (v[i].default ? " : default" : ""))
						}
						// ToDo: why does it run multiple times and first pass is empty
							//      first page load: nothing, got some, got some
							// same tab page reload: nothing, got some
							//    new tab page load: nothing, got some
							//         global rerun: got some
							//        section rerun: got some
						if (res.length == 0) {
							//console.debug("got nothing")
							display("none")
						} else {
							//console.debug("got some", res)
							res.sort()
							display(res)
						}
					}
				} catch(e) {
					display(zB0)
				}
			}
			try {
				if (speechSynthesis.onvoiceschanged !== undefined) {
					populateVoiceList()
					if (typeof speechSynthesis !== "undefined") {
						speechSynthesis.onvoiceschanged = populateVoiceList
					}
				} else {
					display(zB0)
				}
			} catch(e) {
				display(zB0)
			}
		} else {
			display(zD)
		}
	})
}
```

**Comment by abrahamjuliot** [comment]
>  does chameleon cause any issues with your function to enumerate devices? 

Yes, I'm seeing this too. Block works, but not Spoof.

@sereneblue I'm not sure, but it appears the issue is `enumerateDevices` in [mediaSpoof.ts](https://github.com/sereneblue/chameleon/blob/d97da39bd2c38ef100f3d429912e94aa397416c3/src/lib/spoof/mediaSpoof.ts#L141) does not return a promise resolve. `enumerateDevices` in [media.ts](https://github.com/sereneblue/chameleon/blob/728a368f5ea7632d925ac9e09d1971d74c3043bf/src/lib/spoof/media.ts#L8) works and returns a promise resolve.

**Comment by sereneblue** [comment]
> > I noticed that it's being called twice on the page
> 
> Hmmm. Not seen that in my tests (enumerate devices) - maybe I need to debug it more?

@Thorin-Oakenpants enumerateDevices is called from [generic.js](https://github.com/arkenfox/TZP/blob/master/js/generic.js#L530) and [devices.js](https://github.com/arkenfox/TZP/blob/master/js/devices.js#L134).

> > does chameleon cause any issues with your function to enumerate devices?
> 
> Yes, I'm seeing this too. Block works, but not Spoof.
> 
> @sereneblue I'm not sure, but it appears the issue is `enumerateDevices` in [mediaSpoof.ts](https://github.com/sereneblue/chameleon/blob/d97da39bd2c38ef100f3d429912e94aa397416c3/src/lib/spoof/mediaSpoof.ts#L141) does not return a promise resolve. `enumerateDevices` in [media.ts](https://github.com/sereneblue/chameleon/blob/728a368f5ea7632d925ac9e09d1971d74c3043bf/src/lib/spoof/media.ts#L8) works and returns a promise resolve.

I thought that was the issue as well, but it shouldn't make a difference. I've done some debugging and the code doesn't progress past `let devices = await _enumerateDevices()`.

**Comment by abrahamjuliot** [comment]
@Thorin-Oakenpants 
This `promiseRaceFulfilled` function will handle the hanging promise by checking if the promise does not fulfill a `Promise.race` within a set time limit.  

```js
const promiseRaceFulfilled = async ({
    promise,
    responseType, // the promise response type
    limit = 1000 // default ms to fulfill
}) => {
    // set up promise race
    const slowPromise = new Promise(resolve => setTimeout(resolve, limit))
    // await promise race status
    const response = await Promise.race([slowPromise, promise]) // the fastest will win 
        .then(response => response instanceof responseType ? response : 'pending')
        .catch(error => 'rejected')
    return (
        response == 'rejected' || response == 'pending' ? undefined : response
    )
}

// send an async function to new Promise
const getMediaDevices = () => new Promise(async resolve => {

    if (!('mediaDevices' in navigator)) {
        return resolve()
    }

    try {
        // await response
        const response = await promiseRaceFulfilled({
            promise: navigator.mediaDevices.enumerateDevices(),
            responseType: Array
        })
        // exit if not fulfilled
        if (!response) {
            console.error(`enumerateDevices blocked or failed to fulfill`)
            return resolve()
        }

        // else do something with the response
        return resolve(response)
    } catch (error) {
        console.error(error)
        return resolve()
    }
})

getMediaDevices().then(response => console.log(response))

```

**Comment by Thorin-Oakenpants** [comment]
> @Thorin-Oakenpants enumerateDevices is called from [generic.js](https://github.com/arkenfox/TZP/blob/master/js/generic.js#L530) and [devices.js](https://github.com/arkenfox/TZP/blob/master/js/devices.js#L134).

Ahh yes. Instead of running each modular js file as it downloads, I now wait for everything to be ready. So as soon as the first js file (generic.js) lands, I use the time to set a few things up

```js
function run_once() {
	// lets get started while we wait for all the JS modules to arrive

	// immutable
	if ((location.protocol) == "file:") {isFile = true; note_file = " [file:/]"}
	if ((location.protocol) == "https:") {isSecure = true}
	if ("brave" in navigator) {isBrave = true}
	if (!isFF) {runS = false} // sim = FF only
	if ("undefined" != typeof InstallTrigger) {isFF = true}

	//prime up some JS functions
	try {
		navigator.mediaDevices.enumerateDevices().then(function(devices) {})
	} catch(e) {}
	try {
		let v = speechSynthesis.getVoices()
	} catch(e) {}
}
```

What I found was that the devices section perf was always high (of course other functions all trying to run at the same time don't help), and I found that "priming" or "warming" up enumerate devices sped it up immensely (i.e the reported speed)

And on a whim I decided to do the same to speech engines, which solved why I got three returns on page load (see earlier post)

**Comment by abrahamjuliot** [comment]
@sereneblue

This might fix it at [line 64](https://github.com/sereneblue/chameleon/blob/d97da39bd2c38ef100f3d429912e94aa397416c3/src/lib/spoof/mediaSpoof.ts#L64).

```js
value: () => new Promise(async resolve => {
	let devices = await _enumerateDevices()
	
        //....

	return resolve(devices)
}
```

Note, `enumerateDevices` should return a `Function` instead of an `AsyncFunction`. The above should handle this too. 

```js
// Chameleon
navigator.mediaDevices.enumerateDevices.constructor.name // returns "AsyncFunction"

// native
navigator.mediaDevices.enumerateDevices.constructor.name // returns "Function"
```

**Comment by sereneblue** [comment]
> @sereneblue
> 
> This might fix it at [line 64](https://github.com/sereneblue/chameleon/blob/d97da39bd2c38ef100f3d429912e94aa397416c3/src/lib/spoof/mediaSpoof.ts#L64).
> 
> ```js
> value: () => new Promise(async resolve => {
> 	let devices = await _enumerateDevices()
> 	
>         //....
> 
> 	return resolve(devices)
> }
> ```
> 
> Note, `enumerateDevices` should return a `Function` instead of an `AsyncFunction`. The above should handle this too.
> 
> ```js
> // Chameleon
> navigator.mediaDevices.enumerateDevices.constructor.name // returns "AsyncFunction"
> 
> // native
> navigator.mediaDevices.enumerateDevices.constructor.name // returns "Function"
> ```

That works! Thanks, I'll push out an update ASAP.

**Comment by sereneblue** [comment]
Fixed in v0.21.15.

**Comment by Thorin-Oakenpants** [comment]
hmmm .. just tested - it throws an error and there is no spoofing: it also causes other functions to either not lie (or my code sucks), such as timezone + language spoofing was never done (or picked up) <- most likely in the order in which I ask for them

I also tried with various combos of settings: disabling almost all (except user agent cuz I don't want to set that up again, i'm lazy) of them except spoof devices

yes, the UUID is chameleon

![error](https://user-images.githubusercontent.com/16656956/104797497-67149a80-57b6-11eb-8a9c-595bea081478.png)

line 6 is minified

**Comment by sereneblue** [comment]
> hmmm .. just tested - it throws an error and there is no spoofing: it also causes other functions to either not lie (or my code sucks), such as timezone + language spoofing was never done (or picked up) <- most likely in the order in which I ask for them
> 
> I also tried with various combos of settings: disabling almost all (except user agent cuz I don't want to set that up again, i'm lazy) of them except spoof devices
> 
> yes, the UUID is chameleon
> 
> ![error](https://user-images.githubusercontent.com/16656956/104797497-67149a80-57b6-11eb-8a9c-595bea081478.png)
> 
> line 6 is minified

My apologies. It does seem the update I pushed out contained a syntax error. That seemed to have been the "fix" that resolved the issue, haha. I've disabled the update on AMO and will push out an update that will fix the syntax error. The original issue with media devices still seems to persist.

**Comment by abrahamjuliot** [comment]
@sereneblue
It appears the issue is applied when the document contains or injects an iframe.

With spoof on, enter thes code below in the console on these pages:

No iFrames
- https://arkenfox.github.io/TZP/tests/versions.html
- https://canvasblocker.kkapsner.de/test/detectionTest.html
- https://www.blank.org

iFrames
- https://canvasblocker.kkapsner.de/test/iframeTest.html
- https://html.com/tags/iframe/

```js
console.log('pending')
d = await navigator.mediaDevices.enumerateDevices()
console.log('resolved')
console.log(d)
```

**Comment by Thorin-Oakenpants** [comment]
I'm closing this since we now throw a timeout error - but the problem still remains for Chameleon
